### ISSUE TITLE
How to see the output from commands without opening console?

### ISSUE THREAD

**Issue by mabasic** [Stubbs/sublime-vagrant#13]
When i use Vagrant Status or any other command it shows nothing, but when I turn on the console and use any command it shows the output. Is there a way that this can be done automatically?

I am using ST3 on windows.

**Comment by mehdilamaaffar** [comment]
me too

**Comment by benmatselby** [comment]
I've raised a PR (GH-23) that shows the vagrant output to a new sublime view if you turn the configuration on.
