### ISSUE TITLE
Plugin searches for Vagrantfile too often. 

### ISSUE THREAD

**Issue by wldcordeiro** [Stubbs/sublime-vagrant#17]
This plugin is searching for a Vagrantfile constantly according to my console. This shouldn't be happening. If it can't find the file it should fail silently and stop trying. There's some projects of mine where I choose not to include my Vagrantfiles and it's really annoying to constantly be taking hits to performance just for this plugin.

**Comment by benmatselby** [comment]
Sent a PR to resolve this
