### ISSUE TITLE
Redirect output from Vagrant into an output panel

### ISSUE THREAD

**Issue by pradyunsg** [Stubbs/sublime-vagrant#27]
The heading is self-explanatory. Will resolve #13.

**Comment by Stubbs** [comment]
Have you enabled the "output_to_window" setting? That should redirect the output to a panel for you.

**Comment by pradyunsg** [comment]
I do realize that option exists... I'm asking for something different.

What I want is to have the output to come in a build-panel like panel (output panel), not a separate view. `create_output_panel()`, `destroy_output_panel()` that stuff. Not a `new_file` View.

Sidenote: The generated View (made with `new_file`) should be marked as a scratch view. It doesn't matter for output_panel views.

(editted)
