### ISSUE TITLE
A command to run a single command in machine

### ISSUE THREAD

**Issue by pradyunsg** [Stubbs/sublime-vagrant#32]
There are often times when I would want to SSH into the machine, to run a single shell command, possibly to compile a single file. It would be nice if somehow we could allow for a single command to executed through `vagrant ssh -c`, making it a build-system-like thing. 

It would then be possible to create a build-system target command, allowing this to be used as a build target. So much awesome!

**Comment by Kristinita** [comment]
@pradyunsg , what do you think about **#34**?

Thanks.

**Comment by pradyunsg** [comment]
@Kristinita I actually thought of something along the same lines but never said anything about it.

I'm no longer doing any work with Vagrant (or Sublime Text for that matter) so, this doesn't really affect me currently. That said, I would still like to see this fixed.

Since it would still be possible to use the command that implements #34 as a build system command, #34 will obviously supercede this one, fairly specific, request - which is the whole purpose of having something like that.

Personally, I would still use the terminal given that the completion and navigation in the terminal is easier for me to work with. But if someone uses the GUI extensively, this is a useful thing to have. Or write a build command. 😛

**Comment by pradyunsg** [comment]
Closed in favour of #34
